version: '2'
services:
  python:
    build: .
    environment:
      DB_URL: mysql://root:dangerous123@db/cba
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - "/data/authorization/static:/data/static"
  db:
    image: mysql
    # for test no volumes
    ports:
      - "3307:3306"
    volumes:
      - "/data/authorization/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dangerous123
      MYSQL_DATABASE: cba
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]