version: '2'
services:
  python:
    build: .
    ports:
      - "80:80"
    depends_on:
      - java
    links:
      - java:java
  db:
    image: mysql
    ports:
     - "3306:3306"
    # for test no volumes
    volumes:
      - "/data/zx/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dangerous123
      MYSQL_DATABASE: zhengxin
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]